name: Update Requests
run-name: requests @ ${{ github.sha }}

permissions:
  contents: write

concurrency:
  group: delta

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Requests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PA_TOKEN }}

    - name: Export variables
      run: bash .github/scripts/variables.sh >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd ${{ env.sd }}
        sudo pip install -r requirements.txt

    - name: Dump emails
      run: |
        cd ${{ env.sd }}
        python email_dumper.py -U \
          -u '${{ secrets.EMAIL_ADDRESS }}'  \
          -p '${{ secrets.EMAIL_PASSWORD }}' \
          -r '${{ secrets.EMAIL_FOLDER }}'
        
    - name: Parse emails
      run: |
        cd ${{ env.sd }}
        python email_parser.py 

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-update requests.yml
        file_pattern: contribs/requests.yml
