name: Update Requests
run-name: requests @ ${{ github.sha }}

concurrency:
  group: delta

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  update:
    name: Update Requests
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: resources/scripts
    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.PA_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: pip

    - name: Install Python deps
      run: |
        pip install -r requirements.txt

    - name: Process emails
      run: |
        python process_emails.py -p -d --unread \
          --user '${{ secrets.EMAIL_ADDRESS }}' \
          --pass '${{ secrets.EMAIL_PASSWORD }}' \
          --remote '${{ secrets.EMAIL_FOLDER }}' 
        python process_requests.py -qu

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update requests.yml
        file_pattern: contribs/requests.yml
